import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from './models/User.js';
import Product from './models/Product.js';
import Order from './models/Order.js';
import connectDB from './config/db.js';

dotenv.config();
connectDB();

const users = [
  {
    name: 'Admin User',
    email: 'basil59mutuku@gmail.com',
    password: '#Basil123',
    role: 'admin',
  },
  {
    name: 'John Farmer',
    email: 'john@farmer.com',
    password: '123456',
    role: 'farmer',
    location: 'Nairobi, Kenya',
    phone: '+254712345678',
  },
  {
    name: 'Jane Buyer',
    email: 'jane@buyer.com',
    password: '123456',
    role: 'buyer',
    phone: '+254798765432',
  },
  {
    name: 'Mike Farmer',
    email: 'mike@farmer.com',
    password: '123456',
    role: 'farmer',
    location: 'Eldoret, Kenya',
    phone: '+254723456789',
  },
  {
    name: 'Sarah Buyer',
    email: 'sarah@buyer.com',
    password: '123456',
    role: 'buyer',
    phone: '+254789012345',
  },
];

const products = [
  {
    name: 'Fresh Tomatoes',
    description: 'Organic red tomatoes grown locally',
    price: 50,
    category: 'Vegetables',
    quantity: 100,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Organic Carrots',
    description: 'Sweet and crunchy organic carrots',
    price: 40,
    category: 'Vegetables',
    quantity: 80,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1582515073490-39981397c445?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Fresh Spinach',
    description: 'Nutrient-rich fresh spinach leaves',
    price: 30,
    category: 'Vegetables',
    quantity: 50,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Sweet Potatoes',
    description: 'High-quality sweet potatoes',
    price: 60,
    category: 'Vegetables',
    quantity: 120,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Fresh Bananas',
    description: 'Ripe and sweet bananas',
    price: 80,
    category: 'Fruits',
    quantity: 200,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1571771019784-3ff35f4f4277?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Oranges',
    description: 'Juicy navel oranges',
    price: 70,
    category: 'Fruits',
    quantity: 150,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1547514701-42782101795e?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Fresh Mangoes',
    description: 'Sweet and ripe mangoes from local farms',
    price: 90,
    category: 'Fruits',
    quantity: 100,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1553279768-865429fa0078?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Pineapples',
    description: 'Tropical pineapples with golden flesh',
    price: 85,
    category: 'Fruits',
    quantity: 120,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Bell Peppers',
    description: 'Colorful and crunchy bell peppers',
    price: 55,
    category: 'Vegetables',
    quantity: 70,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Eggplant',
    description: 'Fresh purple eggplants',
    price: 45,
    category: 'Vegetables',
    quantity: 60,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Cabbage',
    description: 'Crisp green cabbage heads',
    price: 35,
    category: 'Vegetables',
    quantity: 90,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Avocados',
    description: 'Creamy and nutritious avocados',
    price: 100,
    category: 'Fruits',
    quantity: 80,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Onions',
    description: 'Red onions with strong flavor',
    price: 40,
    category: 'Vegetables',
    quantity: 110,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1582515073490-39981397c445?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Garlic',
    description: 'Fresh garlic bulbs with strong aroma',
    price: 120,
    category: 'Vegetables',
    quantity: 40,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Ginger',
    description: 'Spicy and aromatic ginger roots',
    price: 150,
    category: 'Vegetables',
    quantity: 30,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Turmeric',
    description: 'Golden turmeric roots for cooking',
    price: 180,
    category: 'Vegetables',
    quantity: 25,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Lemongrass',
    description: 'Fragrant lemongrass stalks',
    price: 95,
    category: 'Vegetables',
    quantity: 35,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Kale',
    description: 'Nutrient-dense kale leaves',
    price: 45,
    category: 'Vegetables',
    quantity: 55,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Broccoli',
    description: 'Fresh green broccoli florets',
    price: 65,
    category: 'Vegetables',
    quantity: 45,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Cauliflower',
    description: 'White cauliflower heads',
    price: 55,
    category: 'Vegetables',
    quantity: 50,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Zucchini',
    description: 'Green zucchini squash',
    price: 50,
    category: 'Vegetables',
    quantity: 60,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Pumpkin',
    description: 'Orange pumpkins for cooking',
    price: 75,
    category: 'Vegetables',
    quantity: 80,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Apples',
    description: 'Crisp red apples',
    price: 110,
    category: 'Fruits',
    quantity: 90,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Grapes',
    description: 'Sweet green grapes',
    price: 130,
    category: 'Fruits',
    quantity: 70,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Strawberries',
    description: 'Juicy red strawberries',
    price: 200,
    category: 'Fruits',
    quantity: 40,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Blueberries',
    description: 'Antioxidant-rich blueberries',
    price: 250,
    category: 'Fruits',
    quantity: 30,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Passion Fruits',
    description: 'Tropical passion fruits',
    price: 140,
    category: 'Fruits',
    quantity: 60,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1553279768-865429fa0078?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Pawpaw',
    description: 'Sweet and creamy pawpaw',
    price: 60,
    category: 'Fruits',
    quantity: 100,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Maize',
    description: 'High-quality maize grains',
    price: 25,
    category: 'Grains',
    quantity: 500,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Wheat Flour',
    description: 'Finely milled wheat flour',
    price: 80,
    category: 'Grains',
    quantity: 200,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Fresh Milk',
    description: 'Fresh cow milk from local farms',
    price: 120,
    category: 'Dairy',
    quantity: 50,
    unit: 'liters',
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Cheese',
    description: 'Artisanal cheese made from fresh milk',
    price: 300,
    category: 'Dairy',
    quantity: 20,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Chicken Meat',
    description: 'Fresh chicken meat',
    price: 250,
    category: 'Meat',
    quantity: 30,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Beef',
    description: 'Premium beef cuts',
    price: 400,
    category: 'Meat',
    quantity: 25,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Rice',
    description: 'High-quality long-grain rice',
    price: 90,
    category: 'Grains',
    quantity: 300,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Barley',
    description: 'Nutritious barley grains for cooking',
    price: 70,
    category: 'Grains',
    quantity: 250,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Oats',
    description: 'Rolled oats for breakfast and baking',
    price: 85,
    category: 'Grains',
    quantity: 200,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Quinoa',
    description: 'Protein-rich quinoa seeds',
    price: 150,
    category: 'Grains',
    quantity: 150,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Yogurt',
    description: 'Natural yogurt from fresh milk',
    price: 100,
    category: 'Dairy',
    quantity: 40,
    unit: 'liters',
    images: ['https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Butter',
    description: 'Creamy butter churned from fresh cream',
    price: 250,
    category: 'Dairy',
    quantity: 15,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Cream',
    description: 'Fresh dairy cream for cooking',
    price: 180,
    category: 'Dairy',
    quantity: 20,
    unit: 'liters',
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Cottage Cheese',
    description: 'Soft and creamy cottage cheese',
    price: 220,
    category: 'Dairy',
    quantity: 25,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Pork',
    description: 'Fresh pork cuts from local farms',
    price: 350,
    category: 'Meat',
    quantity: 20,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Lamb',
    description: 'Tender lamb meat',
    price: 450,
    category: 'Meat',
    quantity: 15,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
  {
    name: 'Turkey',
    description: 'Whole turkey for festive meals',
    price: 300,
    category: 'Meat',
    quantity: 10,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400'],
    location: 'Nairobi, Kenya',
    isApproved: true,
  },
  {
    name: 'Goat Meat',
    description: 'Lean and flavorful goat meat',
    price: 380,
    category: 'Meat',
    quantity: 18,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400'],
    location: 'Eldoret, Kenya',
    isApproved: true,
  },
];

const seedDB = async () => {
  try {
    // Drop the username index if it exists (leftover from previous schema)
    try {
      await User.collection.dropIndex('username_1');
      console.log('Dropped username index');
    } catch (error) {
      // Index might not exist, ignore
      console.log('Username index not found or already dropped');
    }

    // Clear existing data
    await User.deleteMany();
    await Product.deleteMany();
    await Order.deleteMany();

    // Create users
    const createdUsers = await User.create(users);
    console.log('Users created:', createdUsers.length);

    // Get farmer users
    const farmers = createdUsers.filter(user => user.role === 'farmer');

    // Assign farmers to products
    const productsWithFarmers = products.map((product, index) => ({
      ...product,
      farmer: farmers[index % farmers.length]._id,
    }));

    // Create products
    const createdProducts = await Product.create(productsWithFarmers);
    console.log('Products created:', createdProducts.length);

    console.log('Database seeded successfully!');
    process.exit();
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDB();
